@baseUrl = http://localhost:3000
@authToken={{authenticate.response.body.accessToken}}
@refreshToken={{authenticate.response.body.refreshToken}}
### get all
GET {{baseUrl}}/recados
?limit=2
&offset=0

### get one
GET {{baseUrl}}/recados/23
 
###
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "3 NOVO Recado",
    "paraId": 12
}

###
PATCH  {{baseUrl}}/recados/23
Authorization: Bearer {{authToken}}
Content-Type: application/json

    {
    "texto": "ATUALIZAR Recado",
    "lido": true

    }



###
DELETE {{baseUrl}}/recados/23
Authorization: Bearer {{authToken}}

////////////////////////////////////////////////////////////////
# PESSOAS
### get all
GET {{baseUrl}}/pessoas
?limit=10
&offset=10
Authorization: Bearer {{authToken}}
### get one
GET {{baseUrl}}/pessoas/10
Authorization: Bearer {{authToken}}
###
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
   "email": "emmaiil@email.com",
   "password": "123456",
   "nome": "Felipe",
   "routePolicies": ["createRecado", "findOneRecado"]
}
###
PATCH  {{baseUrl}}/pessoas/15
Authorization: Bearer {{authToken}}
Content-Type: application/json

    {
    "password": "654321",
    "nome": "Teste"
    }


###
DELETE {{baseUrl}}/pessoas/20
Authorization: Bearer {{authToken}}

////////////////////////////////////////////////////////////////

### AUTH
# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email": "emmaiil@email.com",
    "password": "123456"
}
### Re-Authenticate
# @name re-authenticate
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
 "refreshToken": "{{refreshToken}}"
}