@baseUrl = http://localhost:3000
### APPController GetHello
# @name AppControllerGetHello
GET {{baseUrl}}

### ConceitosAutomaticosController
# @name ConceitosAutomaticosController
# 
GET {{baseUrl}}/conceitos-automatico